bcse_site/bcse_app/urls.py
from django.urls import path

from . import views
from . import api_views

app_name = 'bcse'

urlpatterns = [
    path('', views.home, name='home'),
    path('reservation/<int:id>/edit', views.reservationEdit, name='reservationEdit'),
    path('reservation/<int:id>/view', views.reservationView, name='reservationView'),
    path('reservation/<int:id>/delete', views.reservationDelete, name='reservationDelete'),
    path('reservation/<int:id>/cancel', views.reservationCancel, name='reservationCancel'),
    path('reservation/<int:id>/message', views.reservationMessage, name='reservationMessage'),
    path('reservation/<int:id>/dismissMessages', views.reservationMessageDismiss, name='reservationMessageDismiss'),
    path('reservation/<int:id>/sendconfirmationemail', views.reservationConfirmationEmailSend, name='reservationConfirmationEmailSend'),
    path('reservation/<int:id>/sendfeedbackemail', views.reservationFeedbackEmailSend, name='reservationFeedbackEmailSend'),
    path('reservation/<int:id>/workplace', views.reservationWorkPlaceEdit, name='reservationWorkPlaceEdit'),
    path('reservation/<int:id>/viewconfirmationemail', views.reservationConfirmationEmailView, name='reservationConfirmationEmailView'),
    path('reservation/new', views.reservationEdit, name='reservationNew'),
    path('reservations', views.reservations, name='reservations'),
    path('reservations/search/<str:display>', views.reservationsSearch, name='reservationsSearch'),
    path('reservations/search/', views.reservationsSearch, name='reservationsSearch'),
    path('reservations/dismissMessages', views.reservationMessageDismiss, name='reservationMessageDismiss'),
    path('reservation/<int:reservation_id>/deliveryAddress/edit', views.reservationDeliveryAddressEdit, name='reservationDeliveryAddressEdit'),
    path('reservation/<int:reservation_id>/deliveryAddress/delete', views.reservationDeliveryAddressDelete, name='reservationDeliveryAddressDelete'),
    path('reservation/<int:reservation_id>/update', views.reservationUpdate, name='reservationUpdate'),

    path('reservation/<int:reservation_id>/delivery_pickup_email/edit', views.reservationDeliveryPickupEmailEdit, name='reservationDeliveryPickupEmailEdit'),
    path('reservation/<int:reservation_id>/delivery_pickup_email/<str:email_type>/view', views.reservationDeliveryPickupEmailView, name='reservationDeliveryPickupEmailView'),
    path('reservation/<int:reservation_id>/delivery_pickup_email/<str:email_type>/send', views.reservationDeliveryPickupEmailSend, name='reservationDeliveryPickupEmailSend'),


    path('availability/<int:id>', views.getAvailabilityData, name='getAvailabilityData'),
    path('availability/new', views.getAvailabilityData, name='getAvailabilityData'),
    path('workshop/<int:id>/edit', views.workshopEdit, name='workshopEdit'),
    path('workshop/new', views.workshopEdit, name='workshopNew'),
    path('workshop/<int:id>/view', views.workshopView, name='workshopView'),
    path('workshop/<int:id>/copy', views.workshopCopy, name='workshopCopy'),
    path('workshop/<int:id>/delete', views.workshopDelete, name='workshopDelete'),
    path('workshop/<int:id>/registration_setting/edit', views.workshopRegistrationSetting, name='workshopRegistrationSetting'),
    path('workshop/<int:id>/registrants/', views.workshopRegistrants, name='workshopRegistrants'),
    path('workshop/<int:id>/registrants/search', views.workshopRegistrantsSearch, name='workshopRegistrantsSearch'),
    path('workshop/<int:id>/registrants/upload', views.workshopRegistrantsUpload, name='workshopRegistrantsUpload'),
    path('adminConfiguration/workshops/upload', views.workshopsUpload, name='workshopsUpload'),
    path('adminConfiguration/workshops/registrants/upload', views.allWorkshopsRegistrantsUpload, name='allWorkshopsRegistrantsUpload'),
    path('workshop/<int:workshop_id>/registration/', views.workshopRegistration, name='workshopRegistration'),
    path('workshop/<int:workshop_id>/registration/<int:id>/edit', views.workshopRegistrationEdit, name='workshopRegistrationEdit'),
    path('workshop/<int:workshop_id>/registration/<int:id>/delete', views.workshopRegistrationDelete, name='workshopRegistrationDelete'),
    path('workshop/<int:workshop_id>/registration/<int:id>/cancel', views.workshopRegistrationCancel, name='workshopRegistrationCancel'),
    path('workshop/<int:workshop_id>/registration/questionnaire', views.workshopRegistrationQuestionnaire, name='workshopRegistrationQuestionnaire'),

    path('workshop/<int:workshop_id>/emails', views.workshopEmails, name='workshopEmails'),
    path('workshop/<int:workshop_id>/email/<int:id>/edit', views.workshopEmailEdit, name='workshopEmailEdit'),
    path('workshop/<int:workshop_id>/email/new', views.workshopEmailEdit, name='workshopEmailNew'),
    path('workshop/<int:workshop_id>/email/<int:id>/delete', views.workshopEmailDelete, name='workshopEmailDelete'),

    path('workshop/<int:workshop_id>/registration_emails', views.workshopRegistrationEmails, name='workshopRegistrationEmails'),
    path('workshop/<int:workshop_id>/registration_emails/<int:id>/edit', views.workshopRegistrationEmailEdit, name='workshopRegistrationEmailEdit'),
    path('workshop/<int:workshop_id>/registration_emails/new', views.workshopRegistrationEmailEdit, name='workshopRegistrationEmailNew'),
    path('workshop/<int:workshop_id>/registration_emails/<int:id>/delete', views.workshopRegistrationEmailDelete, name='workshopRegistrationEmailDelete'),
    path('workshop/<int:workshop_id>/registration_emails/<int:id>/preview', views.workshopRegistrationEmailPreview, name='workshopRegistrationEmailPreview'),

    path('workshop/<int:workshop_id>/email/<int:id>/preview', views.workshopEmailPreview, name='workshopEmailPreview'),
    path('workshop/<int:workshop_id>/email/<int:id>/send', views.workshopEmailSend, name='workshopEmailSend'),
    path('workshop/<int:workshop_id>/email/<int:id>/copy', views.workshopEmailCopy, name='workshopEmailCopy'),

    path('workshops/search/<str:display>/<str:period>/', views.workshopsSearch, name='workshopsSearch'),
    path('workshops/search/<str:display>/<str:period>/<str:extra>/', views.workshopsSearch, name='workshopsSearchExtra'),
    path('workshops/<str:display>/<str:period>/', views.workshops, name='workshops'),
    path('workshops/<str:display>/<str:period>/<str:extra>/', views.workshops, name='workshopsExtra'),

    path('signin/', views.userSignin, name='signin'),
    path('signin_redirect/', views.signinRedirect, name='signinRedirect'),
    path('signin/<str:user_email>/', views.userSignin, name='signin'),
    path('signup/', views.userSignup, name='signup'),
    path('signout/', views.userSignout, name='signout'),
    path('userProfile/<int:id>/edit', views.userProfileEdit, name='userProfileEdit'),
    path('userProfile/<int:id>/view', views.userProfileView, name='userProfileView'),
    path('userProfile/<int:id>/delete', views.userProfileDelete, name='userProfileDelete'),
    path('userProfile/<int:id>/workplace', views.userProfileWorkPlace, name='userProfileWorkPlace'),
    path('adminConfiguration/', views.adminConfiguration, name='adminConfiguration'),
    path('adminConfiguration/activity/<int:id>/edit', views.activityEdit, name='activityEdit'),
    path('adminConfiguration/activity/<int:id>/update', views.activityUpdate, name='activityUpdate'),
    path('adminConfiguration/activity/<int:id>/reservation/<int:reservation_id>/update', views.activityUpdate, name='reservationActivityUpdate'),
    path('adminConfiguration/activity/<int:id>/delete', views.activityDelete, name='activityDelete'),
    path('adminConfiguration/activity/new', views.activityEdit, name='activityNew'),
    path('adminConfiguration/activities/', views.activities, name='activities'),
    path('activity/<int:id>/view', views.activityView, name='activityView'),

    path('adminConfiguration/consumable/<int:id>/edit', views.consumableEdit, name='consumableEdit'),
    path('adminConfiguration/consumable/<int:id>/update', views.consumableUpdate, name='consumableUpdate'),
    path('adminConfiguration/consumable/<int:id>/delete', views.consumableDelete, name='consumableDelete'),
    path('adminConfiguration/consumable/new', views.consumableEdit, name='consumableNew'),
    path('adminConfiguration/consumables/', views.consumables, name='consumables'),

    path('adminConfiguration/equipmentType/<int:id>/edit', views.equipmentTypeEdit, name='equipmentTypeEdit'),
    path('adminConfiguration/equipmentType/<int:id>/delete', views.equipmentTypeDelete, name='equipmentTypeDelete'),
    path('adminConfiguration/equipmentType/new', views.equipmentTypeEdit, name='equipmentTypeNew'),
    path('adminConfiguration/equipmentTypes/', views.equipmentTypes, name='equipmentTypes'),
    path('adminConfiguration/availabilityCalendar/', views.adminAvailabilityCalendar, name='adminAvailabilityCalendar'),
    path('adminConfiguration/reservationCalendar/', views.adminReservationCalendar, name='adminReservationCalendar'),
    path('adminConfiguration/reservationCalendar/update', views.adminReservationCalendarUpdate, name='adminReservationCalendarUpdate'),

    path('equipmentType/<int:id>/view', views.equipmentTypeView, name='equipmentTypeView'),
    path('adminConfiguration/equipment/<int:id>/edit', views.equipmentEdit, name='equipmentEdit'),
    path('adminConfiguration/equipment/<int:id>/delete', views.equipmentDelete, name='equipmentDelete'),
    path('adminConfiguration/equipment/<int:id>/overbooking/<int:reservation_id>', views.equipmentOverbookedReservations, name='equipmentOverbookedReservations'),
    path('adminConfiguration/equipment/new', views.equipmentEdit, name='equipmentNew'),
    path('adminConfiguration/equipments/', views.equipments, name='equipments'),

    path('adminConfiguration/baxter_box/usage_report/', views.baxterBoxUsageReport, name='baxterBoxUsageReport'),

bcse_site/bcse_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from ckeditor_uploader import views as ckeditor_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.i18n import JavaScriptCatalog
from bcse_app.forms import SecondaryEmailPasswordResetForm
from bcse_app.views import UserAutocomplete, RegistrantAutocomplete, WorkplaceAutocomplete, WorkplaceAllAutocomplete, FacilitatorAutocomplete

urlpatterns = [
    path('', include('bcse_app.urls', namespace="bcse")),
    path('admin/', admin.site.urls),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             form_class=SecondaryEmailPasswordResetForm,
             template_name='password_reset/password_reset_form.html',
             html_email_template_name='password_reset/password_reset_email.html',
             email_template_name='password_reset/password_reset_email.txt',
             subject_template_name='password_reset/password_reset_subject.txt',
             success_url='/password_reset/done/'
         ), name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset/password_reset_done.html'
         ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset/password_reset_confirm.html',
             success_url='/reset/done/',
             post_reset_login=False,
         ), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset/password_reset_complete.html'
         ), name='password_reset_complete'),

    path('user-autocomplete/', UserAutocomplete.as_view(), name='user-autocomplete'),
    path('facilitator-autocomplete/', FacilitatorAutocomplete.as_view(), name='facilitator-autocomplete'),
    path('registrant-autocomplete/', RegistrantAutocomplete.as_view(), name='registrant-autocomplete'),
    path('workplace-autocomplete/', WorkplaceAutocomplete.as_view(), name='workplace-autocomplete'),
    path('workplace-all-autocomplete/', WorkplaceAllAutocomplete.as_view(), name='workplace-all-autocomplete'),
    re_path(r"^ckeditor/upload/", login_required(ckeditor_views.upload), name="ckeditor_upload"),
    re_path(r"^ckeditor/browse/", never_cache(login_required(ckeditor_views.browse)), name="ckeditor_browse"),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    
]

bcse_site/bcse_app/templates/bcse_app/BaxterBoxBlackoutMessageEdit.html
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      {% if form.instance.id %}
        <h3 class="left"> Edit Blackout Message </h3>
      {% else %}
        <h3 class="left"> Create Blackout Message  </h3>
      {% endif %}
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div id="blackoutMsg" class="msg">
      <ul class="errorlist">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
        {% endfor %}
      </ul>
    </div>
    <form class="form" method="post" action="{% url 'bcse:blackoutMessageEdit' %}" id="formBlackoutMessage">
      {% csrf_token %}
      <div class="modal-body">
        <div class="form-group mb-3">
          <label for="id_{{form.message.name}}" class="form-label"> {{form.message.label}}</label>
          <div class="input-group">
            {{form.message}}
          </div>
          <div class="error">{{ form.message.errors }}</div>
        </div>
        <div class="form-group mb-3">
          <label for="id_{{form.status.name}}" class="form-label"> {{form.status.label}}</label>
          <div class="input-group">
            {{form.status}}
          </div>
          <div class="error">{{ form.end_date.errors }}</div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="form-group buttons">
          <button type="submit" class="btn btn-success blackout_date_save">
            Save
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
  $(function (){
    $('#formBlackoutMessage').submit(function(e){
      e.preventDefault();

      $.ajax({
        type: $(this).attr('method'),
        url: this.action,
        data: $(this).serialize(),
        dataType: 'json',
        success: function(data, status) {
          console.log(status);
          if(data['success'] == true){
            console.log('success');
            $('#general').modal('toggle');
            location.reload();
          }
          else{
            $('#general').html(data['html']);
          }
        },
        error: function(){
          alert("Something went wrong.");
        }
      });
    });

  });
</script>

bcse_site/bcse_app/templates/bcse_app/BaxterBoxInventory.html
{% extends "bcse_app/AdminConfiguration.html" %}
{% load bcse_extras %}
{% load base_extras %}

{% block configuration %}
  <h1 class="center"> Baxter Box Inventory </h1>
   <div class="button-row">
    <a class="btn modal-open" data-bs-toggle="modal" data-bs-target="#general" data-href="{% url 'bcse:inventoryCreate' %}">Create Inventory</a>
  </div>
  {% include "bcse_app/BaxterBoxInventorySearch.html" %}
  <div class="form-group" id="spinner">
    <img src="/static/img/page-loader.gif" class="icon"/>
  </div>
   <div class="search_results">
   </div>
   
  <script type="text/javascript">
    $(function (){
      $('form#inventory_filter_form').submit();      
    });
  </script>
{% endblock %}

bcse_site/bcse_app/templates/bcse_app/ConsumableUpdateModal.html
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="left">Update Consumable {{consumable.name}}</h3>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div id="UpdateMsg" class="msg">
      <ul class="errorlist">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
        {% endfor %}
      </ul>
    </div>

    <form id="formConsumableUpdate" method="post" action="{% url 'bcse:consumableUpdate' consumable.id %}">
      {% csrf_token %}
      {{form.media}}
      <div class="modal-body">
        {{form.id}}

        {% if consumable.image %}
          <div class="form-group mb-3">
            <div class="inventory_image">
              <img src="{{consumable.image.url}}"/>
            </div>
          </div>
        {% endif %}
        <div class="form-group mb-3">
          <label class="form-label">Inventory <button type="button" class="btn" onclick="cloneForm('consumableinventory_set', 'inventory_formset')">Add </button> </label>
          <table class="table table-condensed table-bordered">
            <thead>
              <tr>
                <th width="17%">Storage Location</th>
                <th width="14%">Count</th>
                <th width="35%">Expiration Date</th>
                <th>Notes</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody id="inventory_formset">
              {{formset.management_form}}
              {% for form in formset %}
                {{form.id}}
                <tr class="form-row">
                  <td>
                    {{form.storage_location}}
                    <div class="error">{{ form.storage_location.errors }}</div>
                  </td>
                  <td>
                    {{form.count}}
                    <div class="error">{{ form.count.errors }}</div>
                  </td>
                  <td>
                     <div class="input-group">
                        {{form.expiration_date}}
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                      </div>
                    <div class="error">{{ form.expiration_date.errors }}</div>
                  </td>
                   <td>
                    {{form.notes}}
                    <div class="error">{{ form.notes.errors }}</div>
                  </td>
                  <td>
                    {{form.DELETE.as_hidden}}
                    <button type="button" class="btn btn-xsmall btn-danger delete_inventory"><i class="fa-solid fa-trash-can"></i></button>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="form-group mb-3">
          <label for="id_{{form.notes.name}}">
            {{ form.notes.label|title }}
            {% if form.notes.field.required %}
              (<span class="required">*</span>)
            {% endif %}
          </label>
          <div>{{form.notes}}</div>
          <div class="error">{{ form.notes.errors }}</div>
        </div>
        <div class="form-group mb-3">
          <label for="id_{{form.unit_cost.name}}">
            {{ form.unit_cost.label|title }}  ($)
            {% if form.unit_cost.field.required %}
              (<span class="required">*</span>)
            {% endif %}
          </label>
          <div>{{form.unit_cost}}</div>
          <div class="error">{{ form.unit_cost.errors }}</div>
        </div>
        <div class="form-group mb-3">
          <label for="id_{{form.color.name}}">
            {{ form.color.label }}
            {% if form.color.field.required %}
              (<span class="required">*</span>)
            {% endif %}
          </label>
          <div>{{form.color}}</div>
          <div class="error">{{ form.color.errors }}</div>
        </div>
        <div class="form-group" id="spinner">
          <img src="/static/img/page-loader.gif" class="icon"/>
        </div>
      </div>
      <div class="modal-footer">
        <div class="form-group">
          <button type="submit" class="btn btn-success" id="submit">Save</button>
        </div>
      </div>
    </form>
  </div>
</div>

<script type="text/javascript">
  $(function (){

    $("#formConsumableUpdate").submit(function(e){
      e.preventDefault();

      for (var instance in CKEDITOR.instances) {
        CKEDITOR.instances[instance].updateElement();
      }
      var formData = new FormData(this);

      $.ajax({
        type: $(this).attr('method'),
        url: this.action,
        data: formData,
        cache:false,
        contentType: false,
        processData: false,
        beforeSend: function(){
          $('#formConsumableUpdate #spinner').show();
        },
        complete: function(){
          $('#formConsumableUpdate #spinner').hide();
        },
        success: function(data, status) {
          if(data['success'] == true){
            window.parent.location.reload();
          }
          else{
            $('#kit').html(data['html']);
            bindDateTimePicker();
          }
        },
        error: function(){
          displayErrorDialog();
        }
      });
    });

    bindInventoryRowDelete();

  });
</script>

bcse_site/bcse_app/templates/bcse_app/Facilitators.html
{% extends "bcse_app/AdminConfiguration.html" %}
{% load bcse_extras %}
{% load base_extras %}

{% block configuration %}
  <h1> Facilitators </h1>
  <div class="button-row">
    <a class="btn" href="{% url 'bcse:facilitatorNew' %}" role="button">Create Facilitator</a>
  </div>
  <div class="search_results static">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th> Facilitator ID</th>
          <th> Full Name </th>
          <th> Image </th>
          <th> School </th>
          <th> Bio </th>
          <th> BCSE Role </th>
          <th> Highlight </th>
          <th> Created Date</th>
          <th> Modified Date </th>
          <th> Action </th>
        </tr>
      </thead>
      <tbody>
        {% for facilitator in facilitators %}
          <tr>
            <td> {{facilitator.id}}</td>
            <td> {{facilitator.teacher.user.get_full_name}} </td>
            <td>
              {% if facilitator.teacher.image %}
                <img class="icon" src="{{facilitator.teacher.image.url}}"/>
              {% endif %}
            </td>
            <td> {{facilitator.teacher.work_place}} </td>
            <td class="wysiwyg_content"> {{facilitator.bio|safe}} </td>
            <td> {{facilitator.get_bcse_role_display}} </td>
            <td> {{facilitator.highlight|yesno:"Yes,No"}} </td>
            <td> {{facilitator.created_date|date:"F j, Y g:i A"}}</td>
            <td> {{facilitator.modified_date|date:"F j, Y g:i A"}} </td>
            <td>
              <div class="btn-group">
                <button type="button" class="btn btn-small dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  Action
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'bcse:facilitatorEdit' facilitator.id %}">Edit Facilitator Profile</a>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="dropdown-item modal-open" data-bs-toggle="modal" data-bs-target="#profile" data-href="{% url 'bcse:userProfileEdit' facilitator.teacher.id %}" href="#">Edit User Profile</a>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="dropdown-item delete action" data-href="{% url 'bcse:facilitatorDelete' facilitator.id %}"
                    data-title="the teacher leader <strong>{{facilitator.first_name}} {{facilitator.last_name}}</strong>">
                      Delete
                    </a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

bcse_site/bcse_app/templates/bcse_app/Surveys.html
{% extends "bcse_app/AdminConfiguration.html" %}
{% load bcse_extras %}
{% load base_extras %}

{% block configuration %}
  <h1> Surveys </h1>
  <div class="button-row">
    <a class="btn" href="{% url 'bcse:surveyNew' %}">Create Survey</a>
  </div>
  {% include "bcse_app/SurveysSearch.html" %}
  <div class="form-group" id="spinner">
    <img src="/static/img/page-loader.gif" class="icon"/>
  </div>
  <div class="search_results static">
  </div>
  <script type="text/javascript">
    $(function (){
      $('form#surveys_filter_form').submit();
    });
  </script>
{% endblock %}

bcse_site/bcse_app/templates/bcse_app/TeacherLeadershipOpportunities.html
{% extends "bcse_app/base.html" %}
{% load bcse_extras %}
{% load base_extras %}


{% block content %}
  {{block.super}}
  <div class="content">
    <div class="teacher_opportunity container">
      <h1>Teacher Leadership Opportunities</h1>
      <p class="callout">The Baxter Center for Science Education works to provide a variety of leadership opportunities for local educators. From bringing teachers to Northwestern to conduct research and develop lessons through our Research Experience for Teachers (RET) program to providing tools for teachers to develop their own workshops, we want to partner with educators in finding joy as leaders within their schools, districts, and communities. We also welcome ideas from teachers that link to the BCSE’s mission and priorities. You can read more about the BCSE’s mission on the <a href="{% url 'bcse:aboutBCSE' %}">About Us</a> page.</p>

      <img class="curve right" src="{% staticfile 'img/maryclark.jpeg' %}">
      <p class="callout">Here are some examples of what Teacher Leadership with the BCSE can look like:</p>
      <ul class="callout">
        <li>Apply to be a part of our <a target="_blank" href="{% url 'bcse:standalonePageAliasView' 'ret' %}">Research Experience for Teachers</a> program</li>
        <li>Lead a session at the <a target="_blank" href="{% url 'bcse:standalonePageAliasView' 'baxter_symposium' %}">Baxter Center Symposium</a></li>
        <li>Work with the BCSE to develop an evening or weekend workshop </li>
        <li>Co-facilitate a workshop with one of our existing <a target="_blank" href="{% url 'bcse:aboutTeacherLeaders' %}">teacher leaders</a></li>
        <li>Organize a subject-specific meet-up with support from the BCSE</li>
        <li>Host a <a target="_blank" href="{% url 'bcse:workshops' 'list' 'current' %}">BCSE workshop</a> in your space </li>
        <li>Try out labs or develop supporting materials for the <a target="_blank" href="{% url 'bcse:baxterBoxInfo' %}">Box Program</a></li>
      </ul>
      {% if vignettes %}
        <p class="callout">Click on a story below to read more about how teachers have worked with the BCSE.</p>
        <div class="vignettes search_results list">
          {% include "bcse_app/VignettesTileView.html" %}
        </div>
        <br>
      {% endif %}
      <div class="center">
        <p class="callout center"><strong>Want to get involved?</strong> Tell us more about your ideas by completing the interest survey below!</p>
        <a class="btn" href="?next=/signin/?next=/?next=/survey/5/submission/new">Interest Survey</a>
      </div>
    </div>

    <script type="text/javascript">
      $(function(){

      });
    </script>
  </div>

{% endblock %}

bcse_site/bcse_app/templates/bcse_app/UserProfileTabs.html
{% if userProfile.id %}
  <ul class="nav nav-tabs mb-3">
    <li class="nav-item">
      <label><a class="nav-link active" href="{% url 'bcse:userProfileView' userProfile.id %}">View</a></label>
    </li>
    <li class="nav-item">
      <label><a class="nav-link modal-open" data-bs-toggle="modal" data-bs-target="#profile" data-href="{% url 'bcse:userProfileEdit' userProfile.id %}" href="#">Edit</a></label>
    </li>
  </ul>
{% endif %}

bcse_site/bcse_app/templates/bcse_app/WorkshopAdminView.html
{% extends "bcse_app/AdminConfiguration.html" %}
{% load bcse_extras %}

{% block configuration %}
  <div class="workshop_container">
    {% include "bcse_app/WorkshopView.html" %}
  </div>
{% endblock %}

bcse_site/bcse_app/templates/bcse_app/WorkshopsTabs.html
{% load bcse_extras %}
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <label>
      <a class="nav-link {% if period == 'current' %} active {% endif %}" aria-current="page" href="{% url 'bcse:workshops' display 'current' %}">
        {% if user.is_authenticated and user.userProfile.user_role in 'AS' %}
          Workshops
        {% else %}
          Current Workshops
        {% endif %}
      </a>
    </label>
  </li>
  <li class="nav-item">
    <label><a class="nav-link {% if period != 'current' %} active {% endif %}" aria-current="page" href="{% url 'bcse:workshops' display 'previous' %}">Past Workshop Examples</a></label>
  </li>  
</ul>